// @ts-nocheck
/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: connectedAccountPayments
* Language: JavaScript
* Template: Node
* Generated on 2025-06-25
*/
export const find = (database, filter) => {
    return database.collection("connectedAccountPayments").find(filter);
}

export const findOne = (database, filter) => {
    return database.collection("connectedAccountPayments").findOne(filter);
}

export const deleteOne = (database, filter) => {
    return database.collection("connectedAccountPayments").deleteOne(filter);
}

export const insertOne = (database, filter) => {
    return database.collection("connectedAccountPayments").insertOne(filter);
}

export const updateOne = (database, filter, updateDoc) => {
    return database.collection("connectedAccountPayments").updateOne(filter, updateDoc);
}
