/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: masonicProfiles
* Language: JavaScript
* Template: Node
* Generated on 2025-06-25
*/
export const find = (database, filter) => {
    return database.collection("masonicProfiles").find(filter);
}

export const findOne = (database, filter) => {
    return database.collection("masonicProfiles").findOne(filter);
}

export const deleteOne = (database, filter) => {
    return database.collection("masonicProfiles").deleteOne(filter);
}

export const insertOne = (database, filter) => {
    return database.collection("masonicProfiles").insertOne(filter);
}

export const updateOne = (database, filter, updateDoc) => {
    return database.collection("masonicProfiles").updateOne(filter, updateDoc);
}