// @ts-nocheck
/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: userRoles
* Language: JavaScript
* Template: Node
* Generated on 2025-06-25
*/
export const find = (database, filter) => {
    return database.collection("userRoles").find(filter);
}

export const findOne = (database, filter) => {
    return database.collection("userRoles").findOne(filter);
}

export const deleteOne = (database, filter) => {
    return database.collection("userRoles").deleteOne(filter);
}

export const insertOne = (database, filter) => {
    return database.collection("userRoles").insertOne(filter);
}

export const updateOne = (database, filter, updateDoc) => {
    return database.collection("userRoles").updateOne(filter, updateDoc);
}
