/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: functions
* Language: JavaScript
* Template: Node
* Generated on 2025-06-25
*/
export const find = (database, filter) => {
    return database.collection("functions").find(filter);
}

export const findOne = (database, filter) => {
    return database.collection("functions").findOne(filter);
}

export const deleteOne = (database, filter) => {
    return database.collection("functions").deleteOne(filter);
}

export const insertOne = (database, filter) => {
    return database.collection("functions").insertOne(filter);
}

export const updateOne = (database, filter, updateDoc) => {
    return database.collection("functions").updateOne(filter, updateDoc);
}