/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: organisations
* Language: JavaScript
* Template: Node
* Generated on 2025-06-25
*/
export const find = (database, filter) => {
    return database.collection("organisations").find(filter);
}

export const findOne = (database, filter) => {
    return database.collection("organisations").findOne(filter);
}

export const deleteOne = (database, filter) => {
    return database.collection("organisations").deleteOne(filter);
}

export const insertOne = (database, filter) => {
    return database.collection("organisations").insertOne(filter);
}

export const updateOne = (database, filter, updateDoc) => {
    return database.collection("organisations").updateOne(filter, updateDoc);
}