/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: paymentGateway
 * Language: TypeScript
 * Template: Node
 * Generated on 2025-06-25
 */
import { MongoClient } from "mongodb";

// Connection URI
const uri: string = "mongodb+srv://sample-hostname:27017/?maxPoolSize=20&w=majority";

// Create a new MongoClient
const client: MongoClient = new MongoClient(uri);

async function run(): Promise<void> {
    try {
        // Connect the client to the server (optional starting in v4.7)
        await client.connect();
        // Establish and verify connection
        const database = await client.db("test");
        await database.command({ ping: 1 });
        console.log("Connected successfully to server");
    } finally {
        // Ensures that the client will close when you finish/error
        await client.close();
    }
}

run().catch(console.dir);